# Generated by Django 5.2.1 on 2025-06-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
    ]
