# Generated by Django 5.2.1 on 2025-06-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20250601_1222'),
    ]

    operations = [
    ]
