# Generated by Django 5.2.1 on 2025-06-01 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20250601_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
